### PR TITLE
First Round Edits from Comments

### PR DESCRIPTION
**Pull request by jbae11**
First Round Edits from Comments.
#3

### CODE REVIEW

**Comment by jbae11** [comment]
@gwenchee  let me know what you think. If  you like it, we will ask prof.Huff for review!

**Comment by gwenchee** [comment]
I made some more edits to the current draft and pushed to the jbae11 master branch. Is there a reason why in section 2.3 Analytical solution, you didn't include the fuel fab facilities? If no, i can add them. @jbae11

**Comment by gwenchee** [comment]
@katyhuff Draft 2 is ready for your review.

**Comment by katyhuff** [comment]
Thanks @jbae11 @gwenchee . I'll try to do it in the next week or so. Lots on my plate at the moment, but I'm looking forward to looking it over!

**Comment by katyhuff** [comment]
First pass comments about the PR:

- Only include source files if possible. Source files are what you create directly and are necessary to build the product, like .tex and .bib files. Files built automatically from those source files, like pdf files or executibles, are not source files. Please remove the built pdf. (`git rm`)
- I think some file from someone's latex syncing program has been added by mistake (there is a synctex tar gz file). Please remove it. (`git rm`)
- Generally speaking, to avoid accidentally adding these files, generally avoid `git add *` and don't rely too heavily on gitignore. Add files intentionally, rather than haphazardly.
- You appear to have added the word "hi" at random in the readme. (+hi The repository is part of an effort to add demand-driven deployment)


I haven't yet read the main document. I'll try to do so this weekend.

**Comment by katyhuff** [comment]
I was hoping for a much more complete document than this. Many grammatical errors remain, the discussion is sparse, there are many placeholders ([insert uncertainty]), and the document relies far too heavy on code examples. Please go back through this completely and try to arrive at a complete, camera ready document. For specific comments, you are welcome to drop by my office. Generally, my comment is this: if you remove the code examples from the document, the document makes no sense at all. Rewrite this document in such a way that the code examples are illustrative, referenced by the text, and not essential to the understanding of the tests. 

Other comments:
- [ ] eradicate the use of the word "would"
- [ ] The tests are not appropriate for an itemized list (a list shouldn't span multiple pages... it should be a part of a sentence). Consider subsections or paragraphs for each. OR, if you must use a list, list the main purpose of each test in a single line, then discuss the details of each test elsewhere (e.g. in subsections)
- [ ] The grammar is in need of a re-read (Weird phrases like "The method to how" will become obvious if the document is read aloud by the authors.... )

**Comment by gwenchee** [comment]
@katyhuff  The report is ready for your review.

**Comment by katyhuff** [comment]
Thanks! I'll look it over asap.

**Comment by katyhuff** [comment]
bitmoji

**Pull request merged**
